name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - '^workspaces/*/subnets/**'

jobs: 
  deploy:
    runs-on:
      - ubuntu-latest
    steps:
      - run: "echo 'yeah!'"
    
      