name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - '^workspaces/*/subnets/**'

jobs: 
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.withAutomatedChange }}
      frontend: ${{ steps.filter.outputs.withoutAutomatedChange }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          withoutAutomatedChange:
            - 'workspaces/*/subnets/**'
          withAutomatedChange:
            - '!workspaces/*/subnets/**'
    
  runWithoutAutomatedChange:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.withoutAutomatedChange == 'true' }}
    steps:
      - run: echo "running without automated change"

  runWithAutomatedChange:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.withAutomatedChange == 'true' }}
    steps:
      - run: echo "running with automated change"